version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: auto-universe-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: auto-universe
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - auto-universe-network

  backend:
    build: ./backend
    container_name: auto-universe-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/auto-universe?authSource=admin
      JWT_SECRET: auto-universe-super-secret-jwt-key-docker
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - auto-universe-network

volumes:
  mongodb_data:

networks:
  auto-universe-network:
    driver: bridge
